### ISSUE TITLE
Is there a way reference a team's ELO within adjust() within elo.run()

### ISSUE THREAD

**Issue by z-feldman** [eheinzen/elo#47]
I'm using this package to do ELO ratings for NFL Teams and it's been a huge help so far. One thing I've researched is that teams coming off a bye week have an adjustment, but it's not constant, it's based on how good the team is. Also, games played on Thursdays are slightly different than those on Sundays. Typically it's thought of as the home team having a bigger advantage than usual, but in reality it seems it's just the better of the two teams get the bigger advantage.

Both of these use cases have me wanting to reference each of the team's ELOs within elo.run() so I can check which team is better and how good they are. Thanks!

**Comment by eheinzen** [comment]
A great question.  I've mulled this over quite a bit (even before you mentioned it), but haven't quite narrowed down the right solution.  For instance, I wanted to run fivethirtyeight's NFL elo model, but can't for the same reasons you mention.

Let me think on it some more
