### ISSUE TITLE
Can't calculate scoreline probabilities based on Elo ratings and home/neutral of both teams?

### ISSUE THREAD

**Issue by hrmantovani** [eheinzen/elo#52]
I can predict the outcome of each match but only W/D/L isn't exactly what I want. Firstly, yes I'm new at R. I'm trying to statistically "resimulate" World Cups and its qualifiers since 1930 and I don't know exactly how to forecast it in a good way besides their Elo ratings. I've already scraped one Elo table for each edition of the World Cup, but don't know where to go now. My best shot at the moment is generating scoreline probabilities for each of the matches and then use the sample function to randomly pick a score based on the probabilities.
Another option would be to apply something like the Dixon-Coles model (easy to calculate with packages Regista and Goalmodel) but only based on Elo. Any ideas? Thanks

**Comment by eheinzen** [comment]
So you already have the Elos, or are you trying to generate new Elos?  If the former, then you can use the `elo.prob()` function (as long as those Elos are generated with the same scaling factor as used in this package).  If the latter, then try `elo.run()`.

The problem with the Dixon-Coles model in this case is that it won't take Elo as an input.  You could try a similar theory (Poisson distributions) by using the [Skellam distribution](https://en.wikipedia.org/wiki/Skellam_distribution), but I'm not familiar enough with the regression theory here to give you many pointers.  There is an [R package](https://cran.r-project.org/package=skellam) that may do this for you.

**Comment by hrmantovani** [comment]
I already have the Elos, I'll be using those of one day prior to the WC opening. `elo.prob()` seems perfect but I'm not sure how to consider the chance of draws in its predictions (group matches).

**Comment by eheinzen** [comment]
The [paper](http://www.collective-behavior.com/publ/ELO.pdf) that you linked earlier had a good idea: use an ordered logit model.  Something like this may help (you'll already have the outcome "wins.A" and the difference in Elos "diff", so you don't need to calculate those):

```
> library(elo)
> er <- elo.run(score(points.Home, points.Visitor) ~ team.Home + team.Visitor, data = tournament, k = 20)
> d <- as.data.frame(er)
> d$pre.A <- d$elo.A - d$update.A
> d$pre.B <- d$elo.B - d$update.B
> d$diff <- d$pre.A - d$pre.B
>
> # this is where you should be interested
> polr.model <- MASS::polr(factor(wins.A, levels = (0:2)/2) ~ diff, data = d)
> tail(predict(polr.model, type = "probs"))
           0        0.5         1
51 0.1632053 0.06910044 0.7676942
52 0.4821823 0.10877679 0.4090409
53 0.5548195 0.10430511 0.3408754
54 0.2401718 0.08887370 0.6709545
55 0.4269144 0.10921776 0.4638679
56 0.1053718 0.04913520 0.8454930

```

**Comment by hrmantovani** [comment]
I manage to set the k to vary for each game and also set the initial elos for each team. I also have all the games played from 1872 to 2020. Is there a way to use the eloratings formula? The football one? Thanks for the help!!
