### ISSUE TITLE
neutral() question

### ISSUE THREAD

**Issue by dustinshook** [eheinzen/elo#53]
First off, this is a wonderful package! appreciate all your hard work!

My question is, what is the best way to utilize the neutral() feature for future predictions?

for context I am using the package to explore NBA teams margin of victory, in all my historical data sets neutral games aren't a factor. The NBA is about to have a bunch of neutral location games if the season restarts.

`mcmc_spread <- elo.markovchain(mov(homeTeampts, visitTeampts) ~ homeTeam + visitTeam, data = prep_elo, family = "gaussian", k = 0.6)`

**Comment by eheinzen** [comment]
Sure thing--you can just put in a dummy column for your historical data where no games are neutral (that is, neutral=0), and then add in a column for your future data to indicate which _are_ neutral (neutral=1).

```
> library(elo)
> t1 <- head(tournament, 50)
> t1$neutral <- 0
> em <- elo.markovchain(mov(points.Home, points.Visitor) ~ team.Home + team.Visitor + neutral(neutral),
                        data = t1, family = "gaussian", k = 0.6)
> t2 <- tail(tournament, 6)
> t2$neutral <- c(1, 1, 0, 1, 1, 1)
> predict(em, newdata = t2)
```

**Comment by dustinshook** [comment]
Thank you! Great answer.
