### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by jimmyday12** [eheinzen/elo#57]
Hi - I noticed that your package got removed from CRAN. Just wondering if you have any plans to re-submit?

**Comment by eheinzen** [comment]
Yes, I definitely do.  I didn't realize it had been removed; I can't seem to find any notice in my email.  Sorry about that!  I'll get on it as soon as time allows.

**Comment by jimmyday12** [comment]
No dramas at all - I only noticed when a Vignette I used over on my package which uses it started breaking https://jimmyday12.github.io/fitzRoy/articles/elo-ratings-example.html

Hopefully it's an easy fix - good luck!

**Comment by eheinzen** [comment]
I submitted to CRAN.  If it doesn't get accepted, I'll reopen and continue working
